console.log(JSON.stringify({
  RESEND_API_KEY: process.env.RESEND_API_KEY ? '[PRESENT]' : '[MISSING]',
  RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID ? '[PRESENT]' : '[MISSING]',
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN ? '[PRESENT]' : '[MISSING]',
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
  REPLIT_CONNECTORS_HOSTNAME: process.env.REPLIT_CONNECTORS_HOSTNAME ? '[PRESENT]' : '[MISSING]',
  NODE_ENV: process.env.NODE_ENV
}, null, 2));
